# baseURL: http://192.168.1.73/~max/
languageCode: en-us
relativeURLs: true
theme: index        # 433 righe di codice
enableInlineShortcodes: true
params:
  headers:
    key: Title
    value: Tags
outputs:
  home:
    - HTML
    - JSON
